export interface Company {

    id : string;
    companyGuid : string;
    companyName : string;
    companyId: string;
    companyRegistrationNumber : string;
    companyStatus : string;
    createDate : string;
    email : string;
    faxNumber : string;
    levyNumber : string;
    telNumber : string;
    tradingName : string;
    postalAddressId : string;
    organisationTypeId : string;
    registeredAddressId : string;
    residentialAddressId : string;
    sicCodeId : string;
    recognitionAgreementId : string;
    categorization : string;
    numberOfEmployees1 : string;
    trainingCommitteeInPlace : string;
    financialYearEndDate : string;
    financialYearStartDate : string;  
    locked : string;
    approvalDate : string;
    sarsTradingStatus : string;
    financialYearEndDay : string;
    financialYearEndMonth : string;
    financialYearStartDay : string;
    financialYearStartMonth : string;
    accreditationNumber : string;
    nonSetaCompany : string;
    workplaceApprovalNumber : string;
    setaId : string;
    companySiteNumber : string;
    validiationRanDate : string;
    useTradingNameSetmis : string;
}