export interface PreviousSchools {

    id : string;
    shcoolName: string;
    createDate : string;
    addressee : string;
    allocation : string;
    dmUnName : string;
    dataYear : string;
    demarcationFrom : string;
    demarcationTo : string;
    educatorTwentyEighteen : string;
    eiCircuit : string;
    eiDistrict : string;
    eiRegion : string;
    exDept : string;
    examCentre : string;
    examNo : string;
    gisLatitude : string;
    gisLongitude : string;
    gisSource : string;
    lmUnName : string;
    learnersTwentyEighteen : string;
    nas : string;
    natEmis : string;
    newNatemis : string;
    noFeeSchool : string;
    nodalArea : string;
    officialInstitutionName : string;
    oldNatemis : string;
    ownerBuildings : string;
    ownerLand : string;
    payPointNo : string;
    phasePed : string;
    postalAddress : string;
    province : string;
    provinceCd : string;
    quintile : string;
    sectionTwentyOne : string;
    sectionTwentyOneFunct : string;
    sector : string;
    spCode : string;
    spName : string;
    specialization : string;
    status : string;
    streetAddress : string;
    suburb : string;
    telephone : string;
    townCity : string;
    townshipVillage : string;
    typeDoe : string;
    urbanRural : string;
    wardId : string;

}